Feature/zeroheight
pitagorasampli/ampli-design-system pull request #1
Opened 2021-06-16 17:44 UTC by juliaramosguedes

This PR implements the integration between Zero Height and Style Dictionary

2021-06-16 17:49 UTC, afrodev approved these changes

2021-06-16 19:11 UTC, TiagoHenriqueMoraes approved these changes

2021-06-16 19:14 UTC, lucasrafaele approved these changes

2021-06-17 16:04 UTC, fiuzagr requested changes

2021-06-17 16:04 UTC, fiuzagr commented on config.json
> +              "category": "Color"
@juliaramosguedes . Isso aqui foi a mais, ou é necessário filtrar assim, para depois fazer a conversão para `toLowerCase`?

2021-06-17 16:06 UTC, fiuzagr commented on scripts/preversion_hook.sh
> +ZEROHEIGHT_TOKENS_URL=https://krotondesign.zeroheight.com/api/token_file/f0001be5cf45/share
Fiquei pensando aqui. Será q rola colocar esse passo de download dos tokens no processo de build? Pq assim a gente consegue fazer funcionar local né

2021-06-17 18:08 UTC, juliaramosguedes reviewed
@fiuzagr esse é do iOS. Não to usando conversão toLowerCase nele.

2021-06-17 18:08 UTC, juliaramosguedes commented on config.json
> +              "category": "Color"
@fiuzagr esse é do iOS. Não to usando conversão toLowerCase nele.

2021-06-17 18:10 UTC, juliaramosguedes commented
@fiuzagr foi mal. deletei seu comentário sem querer. queria deletar o meu.
o Color é do iOS. eu não usando conversor nele. só no android.

2021-06-17 18:16 UTC, fiuzagr approved these changes

2021-06-18 11:50 UTC, merged